---
- name: Upgrade packages
  apt:
    update_cache: true
    upgrade: yes

- name: Create the non-root user account
  user:
    name: host
    password: "{{ host_hash }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_comment: "host@{{ ansible_hostname }}"

- name: Read authorized keys of root
  command: cat /root/.ssh/authorized_keys
  register: root_keys

- name: Add same SSH keys as root has
  authorized_key:
    user: host
    state: present
    key: "{{ item }}"
  loop: "{{ root_keys.stdout_lines }}"

- name: Store host's password hash in vars file
  copy:
    content: "host_hash: {{ host_hash }}"
    dest: /home/host/vars_host_hash.yml
    owner: host
    mode: 0600

